#Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

install:
  - pipenv install --dev --ignore-pipfile --deploy

before_script: # code coverage tool
  - echo "Before Script"
  - ls -l
  - echo "End Before Script"
script:
  - pytest --cov-report xml --cov-report term
after_script:
  - echo "After Script"

before_deploy:
  echo "Before Deployment"
deploy:
  skip_cleanup: true
  on:
    branch: main
  provider: script
  script:
    pipenv run python deploy.py